<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_infokatalon.com_fa fa-chevron-up fa-fw fa-1x</name>
   <tag></tag>
   <elementGuidId>40e668ef-573d-4eef-a69e-0f201a6e07a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-chevron-up.fa-fw.fa-1x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='to-top']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>224712fa-b5d2-4474-a69d-f752957662e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-chevron-up fa-fw fa-1x</value>
      <webElementGuid>14d556fc-5278-403b-bdf8-0bad5034918a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;to-top&quot;)/i[@class=&quot;fa fa-chevron-up fa-fw fa-1x&quot;]</value>
      <webElementGuid>4c1b164f-09a5-4a1b-bfb8-9428e063f81c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='to-top']/i</value>
      <webElementGuid>24c450ae-8c91-47b8-8563-bd4dc8ed18aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/a/i</value>
      <webElementGuid>94c83bd8-4518-4415-a164-4764eabd5788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
